# command line: kaggle_get_one_prediction.py -c config/st_gcn/handwash/inference.yaml

base_lr: 0.01
batch_size: 256
config: config/st_gcn/handwash/inference.yaml
debug: false
device: 0
eval_interval: 20
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
model: net.st_gcn.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: hand_wash
        strategy: spatial
    in_channels: 3
    num_class: 7
nesterov: true
num_epoch: 80
num_worker: 4
optimizer: SGD
pavi_log: false
phase: inference
print_log: true
save_interval: 50
save_log: true
save_result: false
show_topk:
- 1
- 5
start_epoch: 0
step: []
test_batch_size: 1
test_feeder_args: {}
train_feeder_args: {}
use_gpu: true
weight_decay: 0.0001
weights: ./work_dir/recognition/handwash/ST_GCN/epoch1000_model.pt
work_dir: ./work_dir/tmp
