# command line: main.py recognition -c config/st_gcn/handwash/train.yaml --step 3

base_lr: 0.1
batch_size: 128
config: config/st_gcn/handwash/train.yaml
config_file_path: /home/hhyg/handwash/code_on_disk_version/Model_training_and_inference/config/st_gcn/handwash/train.yaml
debug: false
device:
- 0
eval_interval: 20
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
max_min_norm: false
model: net.st_gcn.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: hand_wash
        strategy: spatial
    in_channels: 3
    num_class: 1
nesterov: true
num_epoch: 1
num_worker: 4
optimizer: SGD
pavi_log: false
phase: train
print_log: true
rot_max: 0
rot_min: 0
rotation: false
save_interval: 50
save_log: true
save_result: false
show_topk:
- 1
- 5
start_epoch: 0
step: 3
test_batch_size: 128
test_feeder_args:
    data_path: ./data/handwash/test_data.npy
    label_path: ./data/handwash/test_label.pkl
train_feeder_args:
    data_path: ./data/handwash/trainval_data.npy
    label_path: ./data/handwash/trainval_label.pkl
    random_choose: true
    random_move: true
    window_size: 25
use_gpu: true
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/recognition/handwash/ST_GCN/step_3
