weights: ./work_dir/recognition/handwash/ST_GCN/epoch50_model.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/handwash/test_data.npy
  label_path: ./data/handwash/test_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 7
  edge_importance_weighting: True
  graph_args:
    layout: "hand_wash"
    strategy: "spatial"

# test
phase: test
device: 0
test_batch_size: 64
