work_dir: ./work_dir/recognition/handwash/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 25
  data_path: ./data/handwash/trainval_data.npy
  label_path: ./data/handwash/trainval_label.pkl
test_feeder_args:
  data_path: ./data/handwash/test_data.npy
  label_path: ./data/handwash/test_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 7
  edge_importance_weighting: True
  graph_args:
    layout: "hand_wash"
    strategy: "spatial"

# training
device: [0]
batch_size: 128
test_batch_size: 128

#optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 1000
